services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - '9443:9443' # HTTPS web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker
      - portainer_data:/data # Persistent storage
    networks:
      - portainer_network

volumes:
  portainer_data:

networks:
  portainer_network:
    driver: bridge
